[workspace]
authors = ["Neko Ayaka <neko@ayaka.moe>"]
channels = ["conda-forge"]
name = "MotionStreamer"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.8.*"
pip = ">=24.3.1,<25"
openjpeg = ">=2.5.0,<3"
openssl = ">=3.1.8,<4"
packaging = ">=25.0,<26"
pillow = ">=9.4.0,<10"
platformdirs = ">=4.3.6,<5"
gcc = ">=12.4.0,<12.5"
gxx = ">=12.4.0,<12.5"
asttokens = ">=3.0.0,<4"
backcall = ">=0.2.0,<0.3"
blas = ">=2.304,<3"
bzip2 = ">=1.0.8,<2"
comm = ">=0.2.2,<0.3"
certifi = ">=2024.8.30,<2025"
debugpy = ">=1.8.5,<2"
entrypoints = ">=0.4,<0.5"
executing = ">=2.1.0,<3"
ffmpeg = ">=3.2.4,<4"
freetype = ">=2.12.1,<3"
gmp = ">=6.3.0,<7"
gnutls = ">=3.8.9,<4"
ipykernel = ">=6.29.5,<7"
jpeg = ">=9e,<10a"
jupyter_client = ">=8.6.3,<9"
jupyter_core = ">=5.8.1,<6"
lame = ">=3.100,<4"
lcms2 = ">=2.15,<3"
libffi = ">=3.4.6,<4"
libgcc-ng = ">=15.2.0,<16"
libgomp = ">=15.2.0,<16"
libiconv = ">=1.18,<2"
libidn2 = ">=2.3.8,<3"
libpng = ">=1.6.43,<2"
libsodium = ">=1.0.18,<2"
libstdcxx = ">=15.2.0,<16"
libtasn1 = ">=4.20.0,<5"
libtiff = ">=4.5.0,<5"
libunistring = ">=0.9.10,<0.10"
libuv = ">=1.51.0,<2"
libwebp-base = ">=1.6.0,<2"
lz4-c = ">=1.9.4,<2"
mkl = ">=2023.2.0,<2024"
mkl-service = ">=2.4.1,<3"
mkl_fft = ">=1.3.10,<2"
mkl_random = ">=1.2.7,<2"
nest-asyncio = ">=1.6.0,<2"
nettle = ">=3.10.1,<4"
ninja = ">=1.13.2,<2"
olefile = ">=0.47,<0.48"
openh264 = ">=2.6.0,<3"
pickleshare = ">=0.7.5,<0.8"
prompt_toolkit = ">=3.0.48,<4"
pure_eval = ">=0.2.3,<0.3"
pygments = ">=2.18.0,<3"
pyzmq = ">=26.2.0,<27"
readline = ">=8.2,<9"
six = ">=1.16.0,<2"
sqlite = ">=3.46.0,<4"
stack_data = ">=0.6.2,<0.7"
tk = ">=8.6.13,<9"
tornado = ">=6.4.1,<7"
xz = ">=5.8.1,<6"
zeromq = ">=4.3.5,<5"
zstd = ">=1.5.6,<2"
cuda-nvtx = ">=12.0.76,<13"
cuda-nvcc = ">=12.0.76,<13"
cuda-libraries-dev = ">=12.0.0,<13"
cuda-cupti = ">=12.0.90,<13"
cuda = ">=12.0.0,<13"
_libgcc_mutex = ">=0.1,<0.2"
_openmp_mutex = ">=4.5,<5"
ca-certificates = ">=2025.11.12,<2026"
ld_impl_linux-64 = ">=2.45,<3"
libstdcxx-ng = ">=15.2.0,<16"
ncurses = ">=6.5,<7"
ptyprocess = ">=0.7.0,<0.8"
setuptools = ">=75.3.0,<76"
wheel = ">=0.45.1,<0.46"
libxcrypt = ">=4.4.36,<5"

[pypi-dependencies]
absl-py = "==0.13.0"
accelerate = "==1.0.1"
aiohappyeyeballs = "==2.4.3"
aiohttp = "==3.10.11"
aiosignal = "==1.3.1"
annotated-types = "==0.7.0"
antlr4-python3-runtime = "==4.9.3"
async-timeout = "==5.0.1"
attrs = "==24.2.0"
beautifulsoup4 = "==4.12.3"
blis = "==0.7.11"
cachetools = "==4.2.2"
catalogue = "==2.0.10"
charset-normalizer = "==2.0.4"
click = "==8.1.7"
cloudpathlib = "==0.20.0"
confection = "==0.1.5"
cycler = "==0.10.0"
cymem = ">=2.0.11, <3"
decorator = "*"
diffusers = "==0.31.0"
einops = "==0.8.0"
ffmpeg-python = "==0.2.0"
filelock = "==3.16.1"
freetype-py = "==2.5.1"
frozenlist = "==1.5.0"
fsspec = "==2024.2.0"
ftfy = "==6.1.1"
future = "==1.0.0"
fvcore = "==0.1.5.post20221221"
gdown = "==5.2.0"
glfw = "==2.8.0"
google-auth = "==2.36.0"
google-auth-oauthlib = "==0.4.6"
grpcio = "==1.68.0"
h5py = "==3.11.0"
huggingface-hub = "==0.26.2"
idna = "==3.2"
imageio = "==2.9.0"
imageio-ffmpeg = "==0.5.1"
importlib-metadata = "==8.5.0"
iopath = "==0.1.10"
ipdb = "==0.13.9"
ipython = "*"
ipython-genutils = "==0.2.0"
jedi = "*"
jinja2 = "==3.1.3"
joblib = "==1.0.1"
kiwisolver = "==1.3.1"
langcodes = "==3.4.1"
language-data = "==1.3.0"
lightning-utilities = "==0.11.9"
marisa-trie = "==1.2.1"
markdown = "==3.3.4"
markdown-it-py = "==3.0.0"
markupsafe = "==2.1.5"
matplotlib = "==3.4.3"
matplotlib-inline = "*"
mdurl = "==0.1.2"
moviepy = "==0.2.3.1"
mpmath = "==1.3.0"
multidict = "==6.1.0"
murmurhash = "==1.0.11"
natsort = "==8.4.0"
networkx = "==3.0"
numpy = "*"
oauthlib = "==3.1.1"
omegaconf = "==2.3.0"
orjson = "==3.10.15"
pandas = "==1.3.2"
parso = "*"
pexpect = "*"
portalocker = "==3.0.0"
preshed = "==3.0.9"
prompt-toolkit = "*"
propcache = "==0.2.0"
protobuf = "==5.28.3"
psutil = "*"
pyasn1 = "==0.4.8"
pyasn1-modules = "==0.2.8"
pydantic = "==2.10.1"
pydantic-core = "==2.27.1"
pydeprecate = "==0.3.2"
pygame = "==2.6.1"
pyglet = "==2.1.2"
pyopengl = "==3.1.0"
pyparsing = "==2.4.7"
pyrender = "==0.1.45"
pysocks = "==1.7.1"
python-dateutil = "*"
pytorch-lightning = "==1.7.0"
pytorch3d = ">=0.3.0, <0.4"
pytz = "==2021.1"
pyyaml = "==5.4.1"
regex = "==2024.11.6"
requests = "==2.26.0"
requests-oauthlib = "==1.3.0"
rich = "==13.9.4"
rsa = "==4.7.2"
safetensors = "==0.4.5"
scikit-learn = "==0.24.2"
scipy = ">=1.10.1, <2"
sentence-transformers = "==3.2.1"
sentencepiece = "==0.2.0"
shapely = "==2.0.7"
shellingham = "==1.5.4"
sklearn = "==0.0"
smart-open = "==7.0.5"
smplx = "==0.1.28"
soupsieve = "==2.6"
spacy = "==3.7.5"
spacy-legacy = "==3.0.12"
spacy-loggers = "==1.0.5"
srsly = "==2.4.8"
sympy = "==1.13.1"
tabulate = "==0.9.0"
tensorboard = "==2.12.0"
tensorboard-data-server = "==0.7.2"
tensorboard-plugin-wit = "==1.8.0"
termcolor = "==2.4.0"
thinc = ">=8.2.5, <9"
threadpoolctl = "==2.2.0"
timm = "==1.0.12"
tokenizers = "==0.20.3"
toml = "==0.10.2"
tqdm = "==4.62.2"
traitlets = "*"
transformers = "==4.46.3"
triangle = "==20250106"
trimesh = "==4.6.2"
triton = "==3.0.0"
typer = "==0.13.1"
typing-extensions = "==4.12.2"
urllib3 = "==1.26.6"
wasabi = "==1.1.3"
wcwidth = "*"
weasel = "==0.4.1"
werkzeug = "==2.0.1"
wrapt = "==1.17.0"
yacs = "==0.1.8"
yarl = "==1.15.2"
zipp = "*"
clip = { git = "https://github.com/openai/CLIP.git" }
human-body-prior = { git = "https://github.com/nghorbani/human_body_prior.git" }
torchgeometry = ">=0.1.2, <0.2"
torchmetrics = ">=1.5.2, <2"

[target.linux-64.pypi-dependencies]
torch = { version = ">=2.4.1, <3", index = "https://download.pytorch.org/whl/cu121" }
torchaudio = { version = ">=2.4.1, <3", index = "https://download.pytorch.org/whl/cu121" }
torchvision = { version = ">=0.19.1, <1", index = "https://download.pytorch.org/whl/cu121" }
